/* Generated By:JavaCC: Do not edit this line. MiniCParserTreeConstants.java Version 5.0 */
package com.mmdxiaoxin.minicservice.parser;

public interface MiniCParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTPROGRAM = 1;
  public int JJTTYPESPECIFIER = 2;
  public int JJTSTATEMENTBLOCK = 3;
  public int JJTSTATEMENT = 4;
  public int JJTSEQUENCESTATEMENT = 5;
  public int JJTRETURNSTATEMENT = 6;
  public int JJTDECLARATIONSTATEMENT = 7;
  public int JJTASSIGNMENTSTATEMENT = 8;
  public int JJTASSIGNMENTSENTENCE2 = 9;
  public int JJTCONDITIONSTATEMENT = 10;
  public int JJTWHILESTATEMENT = 11;
  public int JJTPARSECONDITION = 12;
  public int JJTROP = 13;
  public int JJTEXPRESSION = 14;
  public int JJTADDITIVEEXPRESSION = 15;
  public int JJTMULTIPLICATIVEEXPRESSION = 16;
  public int JJTUNARYEXPRESSION = 17;
  public int JJTPARSEIDENTIFIER = 18;
  public int JJTPARSEINTEGER = 19;
  public int JJTSWITCHCSTATEMENT = 20;
  public int JJTDOWHILESTATEMENT = 21;
  public int JJTFORSTATEMENT = 22;


  public String[] jjtNodeName = {
    "Start",
    "Program",
    "TypeSpecifier",
    "StatementBlock",
    "Statement",
    "SequenceStatement",
    "ReturnStatement",
    "DeclarationStatement",
    "AssignmentStatement",
    "AssignmentSentence2",
    "ConditionStatement",
    "WhileStatement",
    "parseCondition",
    "Rop",
    "Expression",
    "AdditiveExpression",
    "MultiplicativeExpression",
    "UnaryExpression",
    "parseIdentifier",
    "parseInteger",
    "SwitchCStatement",
    "DoWhileStatement",
    "ForStatement",
  };
}
/* JavaCC - OriginalChecksum=7ed4ea935e161f9821a75bbb69c6eb89 (do not edit this line) */
