/* Generated By:JJTree&JavaCC: Do not edit this line. MiniCParser.java */
package com.mmdxiaoxin.minicservice.parser;
import com.mmdxiaoxin.minicservice.util.*;
import java.io.*;
import java.util.Scanner;

public class MiniCParser/*@bgen(jjtree)*/implements MiniCParserTreeConstants, MiniCParserConstants {/*@bgen(jjtree)*/
  protected JJTMiniCParserState jjtree = new JJTMiniCParserState();
  public QTList qtList = new QTList();
  public StatementType statementType = new StatementType();
  public VariableTable variableTable = new VariableTable();
  public void printQTTable(char [] buffer, FileWriter fos) {
    qtList.printQTTable(fos);
  }

  public String printQTTable() {
    return qtList.printQTTable();
  }

  public static void main(String args []) {
    try {
      //�����ļ�ID
      Scanner scanner = new Scanner(System.in);

      System.out.print("Enter input file nameID (input*.txt): ");
      String inputFileID = scanner.nextLine();

      FileReader reader = new FileReader("input" + inputFileID + ".txt");
      FileReader reader1 = new FileReader("input" + inputFileID + ".txt");
      File outFile = new File("output" + inputFileID + ".txt");
      FileWriter fos = new FileWriter(outFile);
      char [] buffer = new char [1000];
      MiniCParser parser = new MiniCParser(reader);

          // �ʷ�����
      Token token = null;
      SimpleCharStream stream = new SimpleCharStream(reader1);
      MiniCParserTokenManager tokenManager  = new MiniCParserTokenManager(stream);
      token = tokenManager .getNextToken();
      System.out.println("\u8bcd\u6cd5\u5206\u6790:\u005cn");
      String st = new String("\u8bcd\u6cd5\u5206\u6790:\u005cn");
      buffer = st.toCharArray();
      fos.write(buffer); // д���ļ�

      while (token.kind != 0) {
        System.out.println("(" + token.kind + ", " + token.image + ")");
        st = new String("( " + token.kind + "," + token.image + " )" + "\u005cn");
        buffer = st.toCharArray();
        fos.write(buffer);
        token = tokenManager .getNextToken();
      }
      System.out.println("\u005cn");

      // �﷨����
      System.out.println("\u8bed\u6cd5\u5206\u6790: ");
      st = new String("\u005cn\u8bed\u6cd5\u5206\u6790:\u005cn");
      buffer = st.toCharArray();
      fos.write(buffer); // д���ļ�

      SimpleNode n = parser.Start();
      n.dump("", buffer, fos);
      st = new String("Thank you.\u005cn\u005cn");
      buffer = st.toCharArray();
      fos.write(buffer); // д���ļ�
      System.out.println("Thank you.");
      System.out.println("\u005cn");

      // �������
      System.out.println("\u8bed\u4e49\u5206\u6790: \u005cn");
      st = new String("\u8bed\u4e49\u5206\u6790: \u005cn");
      buffer = st.toCharArray();
      fos.write(buffer); // д���ļ�
      parser.printQTTable(buffer, fos);

      // �رղ������ļ�
      fos.close();
    }
    catch (Exception e) {
      System.out.println("Oops.");
      System.out.println(e.getMessage());
    }
  }

  final public SimpleNode Start() throws ParseException {
 /*@bgen(jjtree) Start */
  SimpleNode jjtn000 = new SimpleNode(JJTSTART);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      parseProgram();
    jjtree.closeNodeScope(jjtn000, true);
    jjtc000 = false;
    {if (true) return jjtn000;}
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
    throw new Error("Missing return statement in function");
  }

  final public void parseProgram() throws ParseException {
 /*@bgen(jjtree) parseProgram */
  SimpleNode jjtn000 = new SimpleNode(JJTPARSEPROGRAM);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      parseTypeSpecifier();
      jj_consume_token(MAIN);
      jj_consume_token(LEFT_PAREN);
      jj_consume_token(RIGHT_PAREN);
      jj_consume_token(LEFT_BRACE);
      label_1:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case WHILE:
        case IF:
        case INT:
        case RETURN:
        case VOID:
        case FOR:
        case DO:
        case SWITCH:
        case SHORT:
        case LONG:
        case FLOAT:
        case DOUBLE:
        case CHAR:
        case LEFT_BRACE:
        case IDENTIFIER:
          ;
          break;
        default:
          jj_la1[0] = jj_gen;
          break label_1;
        }
        parseSentenceBlock();
      }
      jj_consume_token(RIGHT_BRACE);
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
  }

  final public String parseTypeSpecifier() throws ParseException {
 /*@bgen(jjtree) parseTypeSpecifier */
  SimpleNode jjtn000 = new SimpleNode(JJTPARSETYPESPECIFIER);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);Token token = null;
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case INT:
        token = jj_consume_token(INT);
    jjtree.closeNodeScope(jjtn000, true);
    jjtc000 = false;
    {if (true) return token.image;}
        break;
      case DOUBLE:
        token = jj_consume_token(DOUBLE);
    jjtree.closeNodeScope(jjtn000, true);
    jjtc000 = false;
    {if (true) return token.image;}
        break;
      case VOID:
        token = jj_consume_token(VOID);
    jjtree.closeNodeScope(jjtn000, true);
    jjtc000 = false;
    {if (true) return token.image;}
        break;
      case FLOAT:
        token = jj_consume_token(FLOAT);
    jjtree.closeNodeScope(jjtn000, true);
    jjtc000 = false;
    {if (true) return token.image;}
        break;
      case CHAR:
        token = jj_consume_token(CHAR);
    jjtree.closeNodeScope(jjtn000, true);
    jjtc000 = false;
    {if (true) return token.image;}
        break;
      case LONG:
        token = jj_consume_token(LONG);
    jjtree.closeNodeScope(jjtn000, true);
    jjtc000 = false;
    {if (true) return token.image;}
        break;
      case SHORT:
        token = jj_consume_token(SHORT);
    jjtree.closeNodeScope(jjtn000, true);
    jjtc000 = false;
    {if (true) return token.image;}
        break;
      default:
        jj_la1[1] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
    throw new Error("Missing return statement in function");
  }

  final public void parseSentenceBlock() throws ParseException {
 /*@bgen(jjtree) parseSentenceBlock */
  SimpleNode jjtn000 = new SimpleNode(JJTPARSESENTENCEBLOCK);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case WHILE:
      case IF:
      case INT:
      case RETURN:
      case VOID:
      case FOR:
      case DO:
      case SWITCH:
      case SHORT:
      case LONG:
      case FLOAT:
      case DOUBLE:
      case CHAR:
      case IDENTIFIER:
        parseSentence();
        break;
      case LEFT_BRACE:
        jj_consume_token(LEFT_BRACE);
        label_2:
        while (true) {
          switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
          case WHILE:
          case IF:
          case INT:
          case RETURN:
          case VOID:
          case FOR:
          case DO:
          case SWITCH:
          case SHORT:
          case LONG:
          case FLOAT:
          case DOUBLE:
          case CHAR:
          case LEFT_BRACE:
          case IDENTIFIER:
            ;
            break;
          default:
            jj_la1[2] = jj_gen;
            break label_2;
          }
          parseSentenceBlock();
        }
        jj_consume_token(RIGHT_BRACE);
        break;
      default:
        jj_la1[3] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
  }

  final public void parseSentence() throws ParseException {
 /*@bgen(jjtree) parseSentence */
  SimpleNode jjtn000 = new SimpleNode(JJTPARSESENTENCE);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case INT:
      case RETURN:
      case VOID:
      case SHORT:
      case LONG:
      case FLOAT:
      case DOUBLE:
      case CHAR:
      case IDENTIFIER:
        parseSequenceSentence();
        break;
      case IF:
        parseConditionSentence();
        break;
      case WHILE:
        parseWhileSentence();
        break;
      case DO:
        parseDoWhile();
        break;
      case SWITCH:
        parseSwitchSentence();
        break;
      case FOR:
        parseForSentence();
        break;
      default:
        jj_la1[4] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
  }

  final public void parseSequenceSentence() throws ParseException {
 /*@bgen(jjtree) parseSequenceSentence */
  SimpleNode jjtn000 = new SimpleNode(JJTPARSESEQUENCESENTENCE);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case INT:
      case VOID:
      case SHORT:
      case LONG:
      case FLOAT:
      case DOUBLE:
      case CHAR:
        parseStatementSentence();
        jj_consume_token(SEMICOLON);
        break;
      case IDENTIFIER:
        parseAssignmentSentence();
        jj_consume_token(SEMICOLON);
        break;
      case RETURN:
        parseReturnSentence();
        jj_consume_token(SEMICOLON);
        break;
      default:
        jj_la1[5] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
  }

  final public void parseReturnSentence() throws ParseException {
 /*@bgen(jjtree) parseReturnSentence */
  SimpleNode jjtn000 = new SimpleNode(JJTPARSERETURNSENTENCE);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(RETURN);
      parseExpression();
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
  }

// �����ظ�����
  final public void parseStatementSentence() throws ParseException {
 /*@bgen(jjtree) parseStatementSentence */
  SimpleNode jjtn000 = new SimpleNode(JJTPARSESTATEMENTSENTENCE);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);Token identifierToken = null;
  Variable variableEntry = new Variable();
  String ty = null;
    try {
      ty = parseTypeSpecifier();
      identifierToken = parseIdentifier();
    variableEntry = new Variable(ty, identifierToken);
    variableTable.addWithCheck(variableEntry);
    statementType.setVariableTable(variableTable);
      label_3:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case COMMA:
          ;
          break;
        default:
          jj_la1[6] = jj_gen;
          break label_3;
        }
        jj_consume_token(COMMA);
        identifierToken = parseIdentifier();
      variableEntry = new Variable(ty, identifierToken);
      variableTable.addWithCheck(variableEntry);
      statementType.setVariableTable(variableTable);
      }
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
  }

  final public void parseAssignmentSentence() throws ParseException {
 /*@bgen(jjtree) parseAssignmentSentence */
  SimpleNode jjtn000 = new SimpleNode(JJTPARSEASSIGNMENTSENTENCE);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);String str1 = null;
  String str2 = null;
  Token assignmentOperator, identifierToken;
  Variable variableEntry = new Variable();
    try {
      identifierToken = parseIdentifier();
    str1 = identifierToken.image;
    variableEntry = variableTable.variableExist(str1);
    if (variableEntry == null)
    {
      System.out.println("\u53d8\u91cf" + str1 + "\u672a\u5b9a\u4e49");
    }
      assignmentOperator = jj_consume_token(ASSIGN);
      str2 = parseExpression();
    jjtree.closeNodeScope(jjtn000, true);
    jjtc000 = false;
    QTInfo qt = new QTInfo(assignmentOperator.image, str2, "_", str1);
    qtList.addQTInfo(qt);
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
  }

  final public void parseAssignmentSentence2() throws ParseException {
 /*@bgen(jjtree) parseAssignmentSentence2 */
  SimpleNode jjtn000 = new SimpleNode(JJTPARSEASSIGNMENTSENTENCE2);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);String str2 = null;
  String str1 = null;
  Token assignmentOperator, identifierToken;
  Variable variableEntry = new Variable();
    try {
      identifierToken = parseIdentifier();
    str1 = identifierToken.image;
    variableEntry = variableTable.variableExist(str1);
    if (variableEntry == null)
    {
      System.out.println("\u53d8\u91cf" + str1 + "\u672a\u5b9a\u4e49");
    }
      assignmentOperator = jj_consume_token(ASSIGN);
      str2 = parseExpression();
    jjtree.closeNodeScope(jjtn000, true);
    jjtc000 = false;
    QTInfo qt = new QTInfo(assignmentOperator.image, str2, "_", str1);
    qtList.addQTInfo(qt);
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
  }

  final public void parseConditionSentence() throws ParseException {
 /*@bgen(jjtree) parseConditionSentence */
  SimpleNode jjtn000 = new SimpleNode(JJTPARSECONDITIONSENTENCE);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);ConditionValue cValue = new ConditionValue();
  int index;
    try {
      jj_consume_token(IF);
      jj_consume_token(LEFT_PAREN);
      cValue = parseCondition();
      jj_consume_token(RIGHT_PAREN);
    cValue.backpatchTrueChain(QTInfo.size + 1);
      parseSentenceBlock();
    cValue.backpatchFalseChain(QTInfo.size + 1);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case ELSE:
        jj_consume_token(ELSE);
      QTInfo qtInfo = new QTInfo("j", "_", "_", "F");
      index = QTInfo.size;
      qtList.addQTInfo(qtInfo);
      cValue.backpatchFalseChain(QTInfo.size + 1);
        parseSentenceBlock();
      qtInfo = qtList.get(index - 1);
      qtInfo.setResult(QTInfo.size + 1);
        break;
      default:
        jj_la1[7] = jj_gen;
        ;
      }
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
  }

  final public void parseWhileSentence() throws ParseException {
 /*@bgen(jjtree) parseWhileSentence */
  SimpleNode jjtn000 = new SimpleNode(JJTPARSEWHILESENTENCE);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);ConditionValue cValue = new ConditionValue();
  int index;
    try {
      jj_consume_token(WHILE);
      jj_consume_token(LEFT_PAREN);
    index = QTInfo.size + 1;
      cValue = parseCondition();
      jj_consume_token(RIGHT_PAREN);
    cValue.backpatchTrueChain(QTInfo.size + 1);
      parseSentenceBlock();
    jjtree.closeNodeScope(jjtn000, true);
    jjtc000 = false;
    QTInfo qtInfo = new QTInfo("j", "_", "_", index);
    qtList.addQTInfo(qtInfo);
    cValue.backpatchFalseChain(QTInfo.size + 1);
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
  }

  final public ConditionValue parseCondition() throws ParseException {
 /*@bgen(jjtree) parseCondition */
  SimpleNode jjtn000 = new SimpleNode(JJTPARSECONDITION);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);String e1 = null;
  String e2 = null;
  Token r = null;
  ConditionValue cValue = new ConditionValue();
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case INTEGER_LITERAL:
      case LEFT_PAREN:
      case IDENTIFIER:
        e1 = parseExpression();
        break;
      default:
        jj_la1[8] = jj_gen;
        ;
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case LESS_THAN:
      case LESS_THAN_EQUAL:
      case GREATER_THAN:
      case GREATER_THAN_EQUAL:
        r = parseRop();
        e2 = parseExpression();
        break;
      default:
        jj_la1[9] = jj_gen;
        ;
      }
    if (r == null || e1 == null)
    {
      if (e1 == null)
      {
        QTInfo qtInfo = new QTInfo("jnz", "_", "_", "T");
        qtList.addQTInfo(qtInfo);
        cValue.mergeTrue(qtInfo);
      }
      else
      {
        QTInfo qtInfo = new QTInfo("jnz", e1, "_", "T");
        qtList.addQTInfo(qtInfo);
        cValue.mergeTrue(qtInfo);
      }
    }
    else
    {
      QTInfo qtInfo = new QTInfo("j" + r.image, e1, e2, "T");
      qtList.addQTInfo(qtInfo);
      cValue.mergeTrue(qtInfo);
    }
    QTInfo qtInfo = new QTInfo("j", "_", "_", "F");
    qtList.addQTInfo(qtInfo);
    cValue.mergeFalse(qtInfo);
    jjtree.closeNodeScope(jjtn000, true);
    jjtc000 = false;
    {if (true) return cValue;}
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
    throw new Error("Missing return statement in function");
  }

  final public Token parseRop() throws ParseException {
 /*@bgen(jjtree) parseRop */
  SimpleNode jjtn000 = new SimpleNode(JJTPARSEROP);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);Token token = null;
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case LESS_THAN:
        token = jj_consume_token(LESS_THAN);
    jjtree.closeNodeScope(jjtn000, true);
    jjtc000 = false;
    {if (true) return token;}
        break;
      case LESS_THAN_EQUAL:
        token = jj_consume_token(LESS_THAN_EQUAL);
    jjtree.closeNodeScope(jjtn000, true);
    jjtc000 = false;
    {if (true) return token;}
        break;
      case GREATER_THAN:
        token = jj_consume_token(GREATER_THAN);
    jjtree.closeNodeScope(jjtn000, true);
    jjtc000 = false;
    {if (true) return token;}
        break;
      case GREATER_THAN_EQUAL:
        token = jj_consume_token(GREATER_THAN_EQUAL);
    jjtree.closeNodeScope(jjtn000, true);
    jjtc000 = false;
    {if (true) return token;}
        break;
      default:
        jj_la1[10] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
    throw new Error("Missing return statement in function");
  }

  final public String parseExpression() throws ParseException {
 /*@bgen(jjtree) parseExpression */
  SimpleNode jjtn000 = new SimpleNode(JJTPARSEEXPRESSION);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);String s = null;
    try {
      s = parseAdditiveExpression();
    jjtree.closeNodeScope(jjtn000, true);
    jjtc000 = false;
    {if (true) return s;}
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
    throw new Error("Missing return statement in function");
  }

  final public String parseAdditiveExpression() throws ParseException {
 /*@bgen(jjtree) parseAdditiveExpression */
  SimpleNode jjtn000 = new SimpleNode(JJTPARSEADDITIVEEXPRESSION);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);String a = null;
  String b = null;
  String result = null;
  Token token = null;
    try {
      a = parseMultiplicativeExpression();
    result = a;
      label_4:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case ADD:
        case SUBTRACT:
          ;
          break;
        default:
          jj_la1[11] = jj_gen;
          break label_4;
        }
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case ADD:
          token = jj_consume_token(ADD);
          break;
        case SUBTRACT:
          token = jj_consume_token(SUBTRACT);
          break;
        default:
          jj_la1[12] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        b = parseMultiplicativeExpression();
      result = VariableNameGenerator.genVariableName();
      QTInfo qtInfo = new QTInfo(token.image, a, b, result);
      qtList.addQTInfo(qtInfo);
      a = result;
      }
    jjtree.closeNodeScope(jjtn000, true);
    jjtc000 = false;
    {if (true) return result;}
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
    throw new Error("Missing return statement in function");
  }

  final public String parseMultiplicativeExpression() throws ParseException {
 /*@bgen(jjtree) parseMultiplicativeExpression */
  SimpleNode jjtn000 = new SimpleNode(JJTPARSEMULTIPLICATIVEEXPRESSION);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);String a = null;
  String b = null;
  String result = null;
  Token token = null;
    try {
      a = parseUnaryExpression();
    result = a;
      label_5:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case MULTIPLY:
        case DIVIDE:
        case MODULO:
          ;
          break;
        default:
          jj_la1[13] = jj_gen;
          break label_5;
        }
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case MULTIPLY:
          token = jj_consume_token(MULTIPLY);
          break;
        case DIVIDE:
          token = jj_consume_token(DIVIDE);
          break;
        case MODULO:
          token = jj_consume_token(MODULO);
          break;
        default:
          jj_la1[14] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        b = parseUnaryExpression();
      result = VariableNameGenerator.genVariableName();
      QTInfo qtInfo = new QTInfo(token.image, a, b, result);
      qtList.addQTInfo(qtInfo);
      a = result;
      }
    jjtree.closeNodeScope(jjtn000, true);
    jjtc000 = false;
    {if (true) return result;}
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
    throw new Error("Missing return statement in function");
  }

  final public String parseUnaryExpression() throws ParseException {
 /*@bgen(jjtree) parseUnaryExpression */
  SimpleNode jjtn000 = new SimpleNode(JJTPARSEUNARYEXPRESSION);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);String str = null;
  Token identifierToken = null;
  Variable variableEntry = new Variable();
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case LEFT_PAREN:
        jj_consume_token(LEFT_PAREN);
        str = parseExpression();
        jj_consume_token(RIGHT_PAREN);
        break;
      case IDENTIFIER:
        identifierToken = parseIdentifier();
      str = identifierToken.image;
      variableEntry = variableTable.variableExist(str);
      if (variableEntry == null)
      {
        System.out.println("\u53d8\u91cf" + str + "\u672a\u5b9a\u4e49");
      }
        break;
      case INTEGER_LITERAL:
        str = parseInteger();
        break;
      default:
        jj_la1[15] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    jjtree.closeNodeScope(jjtn000, true);
    jjtc000 = false;
    {if (true) return str;}
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
    throw new Error("Missing return statement in function");
  }

  final public Token parseIdentifier() throws ParseException {
 /*@bgen(jjtree) parseIdentifier */
  SimpleNode jjtn000 = new SimpleNode(JJTPARSEIDENTIFIER);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);Token token = null;
    try {
      token = jj_consume_token(IDENTIFIER);
    jjtree.closeNodeScope(jjtn000, true);
    jjtc000 = false;
    {if (true) return token;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
    throw new Error("Missing return statement in function");
  }

  final public String parseInteger() throws ParseException {
 /*@bgen(jjtree) parseInteger */
  SimpleNode jjtn000 = new SimpleNode(JJTPARSEINTEGER);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);Token token = null;
    try {
      token = jj_consume_token(INTEGER_LITERAL);
    jjtree.closeNodeScope(jjtn000, true);
    jjtc000 = false;
    {if (true) return token.image;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
    throw new Error("Missing return statement in function");
  }

  final public ConditionValue parseBooler() throws ParseException {
 /*@bgen(jjtree) parseBooler */
  SimpleNode jjtn000 = new SimpleNode(JJTPARSEBOOLER);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);ConditionValue Value = new ConditionValue();
  String str1 = null, str2 = null;
  Token assignmentOperator = null;
  Token op1 = null;
  ConditionValue Value2 = new ConditionValue();
  ConditionValue Valuet = new ConditionValue();
  int qtSize = QTInfo.size;
  QTInfo qt1;
  QTInfo qt2;
    try {
      str1 = parseExpression();
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case LESS_THAN:
      case LESS_THAN_EQUAL:
      case GREATER_THAN:
      case GREATER_THAN_EQUAL:
        assignmentOperator = parseRop();
        str2 = parseExpression();
        break;
      default:
        jj_la1[16] = jj_gen;
        ;
      }
    if (assignmentOperator != null)
    {
      qt1 = new QTInfo("J" + assignmentOperator.image, str1, str2, QTInfo.size + 3);
      qtList.addQTInfo(qt1);
    }
    else
    {
      qt1 = new QTInfo("Jnz", str1, "_", QTInfo.size + 3);
      qtList.addQTInfo(qt1);
    }
    qt2 = new QTInfo("J", "_", "_", "F");
    qtList.addQTInfo(qt2);
    Value.mergeFalse(qt2);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case OR:
      case AND:
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case AND:
          op1 = jj_consume_token(AND);
        Valuet = new ConditionValue();
        Valuet.mergeFalse(qt2);
        Value.backpatchTrueChain(QTInfo.size + 1);
          break;
        case OR:
          op1 = jj_consume_token(OR);
          Valuet.mergeFalse(qt2);
          Valuet.backpatchFalseChain(QTInfo.size + 1);
          Value.backpatchFalseChain(QTInfo.size + 1);
          break;
        default:
          jj_la1[17] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        Value2 = parseBooler();
      if (op1.image.equals("&&"))
      {
        Value2.mergeFalse(qt2);
        Value2.backpatchFalseChain(QTInfo.size + 1);
      }
      if (op1.image.equals("||"))
      {
        Value2.mergeTrue(qt1);
        Value2.backpatchTrueChain(QTInfo.size + 1);
      }
      {if (true) return Value2;}
        break;
      default:
        jj_la1[18] = jj_gen;
        ;
      }
    jjtree.closeNodeScope(jjtn000, true);
    jjtc000 = false;
    {if (true) return Value;}
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
    throw new Error("Missing return statement in function");
  }

  final public void parseSwitchSentence() throws ParseException {
 /*@bgen(jjtree) parseSwitchSentence */
  SimpleNode jjtn000 = new SimpleNode(JJTPARSESWITCHSENTENCE);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);ConditionValue Value = new ConditionValue();
  String str1 = null;
  String str2 = null;
  int qtSize = QTInfo.size;
  Token tok;
  Token tokx;
    try {
      jj_consume_token(SWITCH);
      jj_consume_token(LEFT_PAREN);
      tok = parseIdentifier();
      jj_consume_token(RIGHT_PAREN);
      jj_consume_token(LEFT_BRACE);
      label_6:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case CASE:
          ;
          break;
        default:
          jj_la1[19] = jj_gen;
          break label_6;
        }
        jj_consume_token(CASE);
        tokx = jj_consume_token(INTEGER_LITERAL);
      QTInfo qt1;
      if (tokx != null)
      {
        qt1 = new QTInfo("case", tok.image, tokx.image, QTInfo.size + 3);
        qtList.addQTInfo(qt1);
        Value.backpatchFalseChain(QTInfo.size);
        Value = new ConditionValue();
      }
      else
      {
        qt1 = new QTInfo("Jnz", tok.image, "_", QTInfo.size + 3);
        qtList.addQTInfo(qt1);
      }
      QTInfo qt2 = new QTInfo("J", "_", "_", "F");
      qtList.addQTInfo(qt2);
      Value.mergeFalse(qt2);
      Value.backpatchFalseChain(QTInfo.size + 2);
        jj_consume_token(COLON);
        label_7:
        while (true) {
          switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
          case WHILE:
          case IF:
          case INT:
          case RETURN:
          case VOID:
          case FOR:
          case DO:
          case SWITCH:
          case SHORT:
          case LONG:
          case FLOAT:
          case DOUBLE:
          case CHAR:
          case LEFT_BRACE:
          case IDENTIFIER:
            ;
            break;
          default:
            jj_la1[20] = jj_gen;
            break label_7;
          }
          parseSentenceBlock();
        }
        jj_consume_token(BREAK);
        jj_consume_token(SEMICOLON);
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case DFLT:
        jj_consume_token(DFLT);
        jj_consume_token(COLON);
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case WHILE:
        case IF:
        case INT:
        case RETURN:
        case VOID:
        case FOR:
        case DO:
        case SWITCH:
        case SHORT:
        case LONG:
        case FLOAT:
        case DOUBLE:
        case CHAR:
        case LEFT_BRACE:
        case IDENTIFIER:
          parseSentenceBlock();
          break;
        default:
          jj_la1[21] = jj_gen;
          ;
        }
        jj_consume_token(BREAK);
        jj_consume_token(SEMICOLON);
        break;
      default:
        jj_la1[22] = jj_gen;
        ;
      }
      jj_consume_token(RIGHT_BRACE);
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
  }

  final public void parseDoWhile() throws ParseException {
 /*@bgen(jjtree) parseDoWhile */
  SimpleNode jjtn000 = new SimpleNode(JJTPARSEDOWHILE);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);int QTSize = QTInfo.size;
  ConditionValue Value = null;
  String str1 = null;
  String str2 = null;
  Token assignmentOperator = null;
    try {
      jj_consume_token(DO);
      parseSentenceBlock();
      jj_consume_token(WHILE);
      jj_consume_token(LEFT_PAREN);
      Value = parseBooler();
      jj_consume_token(RIGHT_PAREN);
      jj_consume_token(SEMICOLON);
    Value.backpatchTrueChain(QTSize + 1);
    jjtree.closeNodeScope(jjtn000, true);
    jjtc000 = false;
    Value.backpatchFalseChain(QTInfo.size + 1);
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
  }

  final public void parseForSentence() throws ParseException {
 /*@bgen(jjtree) parseForSentence */
  SimpleNode jjtn000 = new SimpleNode(JJTPARSEFORSENTENCE);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);ConditionValue cValue = new ConditionValue();
  int index;
    try {
      jj_consume_token(FOR);
      jj_consume_token(LEFT_PAREN);
    index = QTInfo.size + 1;
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case INT:
      case VOID:
      case SHORT:
      case LONG:
      case FLOAT:
      case DOUBLE:
      case CHAR:
      case IDENTIFIER:
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case INT:
        case VOID:
        case SHORT:
        case LONG:
        case FLOAT:
        case DOUBLE:
        case CHAR:
          parseStatementSentence();
          break;
        case IDENTIFIER:
          parseAssignmentSentence2();
          break;
        default:
          jj_la1[23] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        break;
      default:
        jj_la1[24] = jj_gen;
        ;
      }
      jj_consume_token(SEMICOLON);
      cValue = parseCondition();
      jj_consume_token(SEMICOLON);
      label_8:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case IDENTIFIER:
          ;
          break;
        default:
          jj_la1[25] = jj_gen;
          break label_8;
        }
        parseAssignmentSentence2();
      }
      jj_consume_token(RIGHT_PAREN);
    cValue.backpatchTrueChain(QTInfo.size + 1);
      parseSentenceBlock();
    jjtree.closeNodeScope(jjtn000, true);
    jjtc000 = false;
    QTInfo qtInfo = new QTInfo("j", "_", "_", index);
    qtList.addQTInfo(qtInfo);
    cValue.backpatchFalseChain(QTInfo.size + 1);
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
  }

  /** Generated Token Manager. */
  public MiniCParserTokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private int jj_gen;
  final private int[] jj_la1 = new int[26];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static private int[] jj_la1_2;
  static {
      jj_la1_init_0();
      jj_la1_init_1();
      jj_la1_init_2();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0x1dd8000,0x140000,0x1dd8000,0x1dd8000,0x1dd8000,0x1c0000,0x0,0x20000,0x80,0x0,0x0,0x0,0x0,0x0,0x0,0x80,0x0,0x0,0x0,0x2000000,0x1dd8000,0x1dd8000,0x0,0x140000,0x140000,0x0,};
   }
   private static void jj_la1_init_1() {
      jj_la1_1 = new int[] {0x7c00,0x7c00,0x7c00,0x7c00,0x7c00,0x7c00,0x0,0x0,0x0,0x0,0x0,0x600000,0x600000,0x3800000,0x3800000,0x0,0x0,0x0,0x0,0x0,0x7c00,0x7c00,0x8000,0x7c00,0x7c00,0x0,};
   }
   private static void jj_la1_init_2() {
      jj_la1_2 = new int[] {0x202000,0x0,0x202000,0x202000,0x200000,0x200000,0x100,0x0,0x200400,0xf,0xf,0x0,0x0,0x0,0x0,0x200400,0xf,0x60,0x60,0x0,0x202000,0x202000,0x0,0x200000,0x200000,0x200000,};
   }

  /** Constructor with InputStream. */
  public MiniCParser(InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public MiniCParser(InputStream stream, String encoding) {
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new MiniCParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 26; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jjtree.reset();
    jj_gen = 0;
    for (int i = 0; i < 26; i++) jj_la1[i] = -1;
  }

  /** Constructor. */
  public MiniCParser(Reader stream) {
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new MiniCParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 26; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jjtree.reset();
    jj_gen = 0;
    for (int i = 0; i < 26; i++) jj_la1[i] = -1;
  }

  /** Constructor with generated Token Manager. */
  public MiniCParser(MiniCParserTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 26; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(MiniCParserTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jjtree.reset();
    jj_gen = 0;
    for (int i = 0; i < 26; i++) jj_la1[i] = -1;
  }

  private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }


/** Get the next Token. */
  final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  private int[] jj_expentry;
  private int jj_kind = -1;

  /** Generate ParseException. */
  public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[88];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 26; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
          if ((jj_la1_1[i] & (1<<j)) != 0) {
            la1tokens[32+j] = true;
          }
          if ((jj_la1_2[i] & (1<<j)) != 0) {
            la1tokens[64+j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 88; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

}
