/* Generated By:JJTree&JavaCC: Do not edit this line. MiniCParserConstants.java */
package com.mmdxiaoxin.minicservice.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MiniCParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int WHILE = 7;
  /** RegularExpression Id. */
  int IF = 8;
  /** RegularExpression Id. */
  int ELSE = 9;
  /** RegularExpression Id. */
  int INT = 10;
  /** RegularExpression Id. */
  int RETURN = 11;
  /** RegularExpression Id. */
  int VOID = 12;
  /** RegularExpression Id. */
  int MAIN = 13;
  /** RegularExpression Id. */
  int FOR = 14;
  /** RegularExpression Id. */
  int DO = 15;
  /** RegularExpression Id. */
  int SWITCH = 16;
  /** RegularExpression Id. */
  int CASE = 17;
  /** RegularExpression Id. */
  int BREAK = 18;
  /** RegularExpression Id. */
  int CONTINUE = 19;
  /** RegularExpression Id. */
  int GOTO = 20;
  /** RegularExpression Id. */
  int SIZEOF = 21;
  /** RegularExpression Id. */
  int TYPEDEF = 22;
  /** RegularExpression Id. */
  int STRUCT = 23;
  /** RegularExpression Id. */
  int UNION = 24;
  /** RegularExpression Id. */
  int ENUM = 25;
  /** RegularExpression Id. */
  int REGISTER = 26;
  /** RegularExpression Id. */
  int AUTO = 27;
  /** RegularExpression Id. */
  int EXTERN = 28;
  /** RegularExpression Id. */
  int STATIC = 29;
  /** RegularExpression Id. */
  int CONST = 30;
  /** RegularExpression Id. */
  int VOLATILE = 31;
  /** RegularExpression Id. */
  int SIGNED = 32;
  /** RegularExpression Id. */
  int UNSIGNED = 33;
  /** RegularExpression Id. */
  int SHORT = 34;
  /** RegularExpression Id. */
  int LONG = 35;
  /** RegularExpression Id. */
  int FLOAT = 36;
  /** RegularExpression Id. */
  int DOUBLE = 37;
  /** RegularExpression Id. */
  int CHAR = 38;
  /** RegularExpression Id. */
  int DFLT = 39;
  /** RegularExpression Id. */
  int TRUE = 40;
  /** RegularExpression Id. */
  int FALSE = 41;
  /** RegularExpression Id. */
  int ADD = 42;
  /** RegularExpression Id. */
  int SUBTRACT = 43;
  /** RegularExpression Id. */
  int MULTIPLY = 44;
  /** RegularExpression Id. */
  int DIVIDE = 45;
  /** RegularExpression Id. */
  int MODULO = 46;
  /** RegularExpression Id. */
  int ASSIGN = 47;
  /** RegularExpression Id. */
  int PLUS_ASSIGN = 48;
  /** RegularExpression Id. */
  int MINUS_ASSIGN = 49;
  /** RegularExpression Id. */
  int MUL_ASSIGN = 50;
  /** RegularExpression Id. */
  int DIV_ASSIGN = 51;
  /** RegularExpression Id. */
  int MOD_ASSIGN = 52;
  /** RegularExpression Id. */
  int LESS_THAN = 53;
  /** RegularExpression Id. */
  int LESS_THAN_EQUAL = 54;
  /** RegularExpression Id. */
  int GREATER_THAN = 55;
  /** RegularExpression Id. */
  int GREATER_THAN_EQUAL = 56;
  /** RegularExpression Id. */
  int NOT_EQUAL = 57;
  /** RegularExpression Id. */
  int OR = 58;
  /** RegularExpression Id. */
  int AND = 59;
  /** RegularExpression Id. */
  int NOT = 60;
  /** RegularExpression Id. */
  int SEMICOLON = 61;
  /** RegularExpression Id. */
  int COMMA = 62;
  /** RegularExpression Id. */
  int COLON = 63;
  /** RegularExpression Id. */
  int LEFT_PAREN = 64;
  /** RegularExpression Id. */
  int RIGHT_PAREN = 65;
  /** RegularExpression Id. */
  int RIGHT_BRACE = 66;
  /** RegularExpression Id. */
  int LEFT_BRACE = 67;
  /** RegularExpression Id. */
  int LEFT_BRACKET = 68;
  /** RegularExpression Id. */
  int RIGHT_BRACKET = 69;
  /** RegularExpression Id. */
  int HASH = 70;
  /** RegularExpression Id. */
  int AMPERSAND = 71;
  /** RegularExpression Id. */
  int PIPE = 72;
  /** RegularExpression Id. */
  int DOT = 73;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 74;
  /** RegularExpression Id. */
  int DECIMAL_LITERAL = 75;
  /** RegularExpression Id. */
  int HEX_LITERAL = 76;
  /** RegularExpression Id. */
  int OCTAL_LITERAL = 77;
  /** RegularExpression Id. */
  int FLOATING_POINT_LITERAL = 78;
  /** RegularExpression Id. */
  int EXPONENT = 79;
  /** RegularExpression Id. */
  int CHARACTER_LITERAL = 80;
  /** RegularExpression Id. */
  int STRING_LITERAL = 81;
  /** RegularExpression Id. */
  int _NUM_CHAR = 82;
  /** RegularExpression Id. */
  int _ESCAPED_CHAR = 83;
  /** RegularExpression Id. */
  int _TERM_START_CHAR = 84;
  /** RegularExpression Id. */
  int _TERM_CHAR = 85;
  /** RegularExpression Id. */
  int _WHITESPACE = 86;
  /** RegularExpression Id. */
  int IDENTIFIER = 87;
  /** RegularExpression Id. */
  int LETTER = 88;
  /** RegularExpression Id. */
  int DIGIT = 89;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "\"while\"",
    "\"if\"",
    "\"else\"",
    "\"int\"",
    "\"return\"",
    "\"void\"",
    "\"main\"",
    "\"for\"",
    "\"do\"",
    "\"switch\"",
    "\"case\"",
    "\"break\"",
    "\"continue\"",
    "\"goto\"",
    "\"sizeof\"",
    "\"typedef\"",
    "\"struct\"",
    "\"union\"",
    "\"enum\"",
    "\"register\"",
    "\"auto\"",
    "\"extern\"",
    "\"static\"",
    "\"const\"",
    "\"volatile\"",
    "\"signed\"",
    "\"unsigned\"",
    "\"short\"",
    "\"long\"",
    "\"float\"",
    "\"double\"",
    "\"char\"",
    "\"default\"",
    "\"true\"",
    "\"false\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"=\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"%=\"",
    "\"<\"",
    "\"<=\"",
    "\">\"",
    "\">=\"",
    "\"!=\"",
    "\"||\"",
    "\"&&\"",
    "\"!\"",
    "\";\"",
    "\",\"",
    "\":\"",
    "\"(\"",
    "\")\"",
    "\"}\"",
    "\"{\"",
    "\"[\"",
    "\"]\"",
    "\"#\"",
    "\"&\"",
    "\"|\"",
    "\".\"",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<EXPONENT>",
    "<CHARACTER_LITERAL>",
    "<STRING_LITERAL>",
    "<_NUM_CHAR>",
    "<_ESCAPED_CHAR>",
    "<_TERM_START_CHAR>",
    "<_TERM_CHAR>",
    "<_WHITESPACE>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
  };

}
